build(npm): update to latest ember-cli
dollarshaveclub/ember-cli-anybar pull request #17
Opened 2018-07-07 19:15 UTC by alexdiliberto

closes #16

2018-07-24 21:11 UTC, arjansingh commented
@alexdiliberto Thank you. We need to set up some CI on this repo first before merging this. Stay tuned. We'll find some time for that.

2018-07-30 18:18 UTC, stefkoenig commented
@alexdiliberto Thanks so much for all the work in this PR! CI is now setup on the repo. Mind rebasing with master/fixing the conflicts and then we'll review and get this in?

2018-07-30 22:34 UTC, alexdiliberto commented
👍 Sure thing, thanks @stefkoenig. I updated the the origin PR with merge conflict fixes. Should be good to go

2018-07-30 23:50 UTC, stefkoenig requested changes
Hey! Looks good - just some nitpicky style guide requests mostly then we can get this merged in! Since they are nitpicky, I'm happy to check out your branch, make the changes, and push on top of it if you'd prefer. Just let me know. :)

2018-07-30 23:50 UTC, stefkoenig commented on .eslintignore
> +/bower_components/
Can `bower_components` be killed here since you're removing them completely? 

Also according to ESLint Docs:

> In addition to any patterns in a .eslintignore file, ESLint always ignores files in /node_modules/* and /bower_components/*.
https://eslint.org/docs/user-guide/configuring

2018-07-30 23:50 UTC, stefkoenig commented on .eslintignore
> +/dist/
mind killing the ones below that I added to avoid duplication?

2018-07-30 23:50 UTC, stefkoenig commented on .eslintignore
> +/blueprints/*/files/
It looks like the beginning and ending `/`s are not necessary

2018-07-30 23:50 UTC, stefkoenig commented on .eslintignore
> +assets
please add a blank line at the end of this and all other files. thanks!

2018-07-30 23:50 UTC, stefkoenig commented on .gitignore
> +/dist/
don't think `/` is necessary here

2018-07-30 23:50 UTC, stefkoenig commented on .gitignore
> +/bower_components/
can this line be killed completely since `bower_components` are being removed?

2018-07-30 23:50 UTC, stefkoenig commented on .npmignore
> +.node_modules.ember-try/
is `/` needed at end here?

2018-07-30 23:50 UTC, stefkoenig commented on package.json
>    "version": "0.6.0",
can we increment the version to `0.7.0`, please?

2018-07-31 02:47 UTC, alexdiliberto commented on .eslintignore
> +assets
I'll just revert this back to the one you had on your previous CI-related PR. These were all added from the default Ember CLI blueprint

2018-07-31 02:50 UTC, alexdiliberto commented on .gitignore
> +/bower_components/
Just reverting back this as well

2018-07-31 17:51 UTC, stefkoenig approved these changes

2018-07-31 17:52 UTC, merged